# Preparation see DOCKER_DEV.md

volumes:
  build:

services:
  app:
    image: archivesspace-plugin-development:latest
    command: sleep infinity
    depends_on:
      - db
      - solr
    env_file:
      - .env.docker.dev
    volumes:
      - .:/archivesspace
      - build:/archivesspace/build
    ports:
      - 1234:1234 # Ruby remote debugger backend
      - 1235:1235 # Ruby remote debugger frontend
      - 3000:3000 # backend / api
      - 3001:3001 # frontend / staff
      - 4567:4567 # public
      - 4568:4568 # oai2
      - 5005:5005 # Remote Java debug
      - 9876:9876 # pry-remote
  db:
    image: mysql:8
    command: --character-set-server=UTF8MB4 --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --log_bin_trust_function_creators=1
    ports:
      - "3308:3306"
    env_file:
      - .env.docker.db
    volumes:
      - ./mysql:/var/lib/mysql
  solr:
    build:
      context: ./solr
    image: archivesspace/solr:latest
    command: solr-create -p 8983 -c archivesspace -d archivesspace
    ports:
      - "8985:8983"
